### ISSUE TITLE
<!-- [if IE]> error: Unknown pseudo class []

### ISSUE THREAD

**Issue by Meai1** [kevin-montrose/More#10]
Looks like More can't process conditional css

**Comment by kevin-montrose** [comment]
That's not really CSS, it's an IE specific [extension to HTML](http://msdn.microsoft.com/en-us/library/ms537512%28v=vs.85%29.aspx) that happens to work enough in CSS to have gotten some traction there.

I'm a little remiss to pass that through.  However, the error message is pretty dodge, and should be fixed.
